name: CreateMKDocsNavigation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest   

    env:
      Solution_Name: CreateMKDocsNavigation.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c release --no-restore
      
    - name: Publish linux
      run: dotnet publish -p:PublishSingleFile=true -r linux-x64 -c Release --self-contained true -p:PublishTrimmed=true
      
    - name: Publish osx
      run: dotnet publish -p:PublishSingleFile=true -r osx-x64 -c Release --self-contained true -p:PublishTrimmed=true
      
    - name: Publish windows
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained true -p:PublishTrimmed=true
      
    - name: Upload a Build Artifact linux
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: CreateMKDocsNavigation-linux-x64 #.zip will be added automatically
        path: bin/Release/net7.0/linux-x64/publish/*.*
      
    - name: Upload a Build Artifact osx
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: CreateMKDocsNavigation-osx-x64 #.zip will be added automatically
        path: bin/Release/net7.0/osx-x86/publish/*.*
      
    - name: Upload a Build Artifact windows
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: CreateMKDocsNavigation-win-x64 #.zip will be added automatically
        path: bin/Release/net7.0/win-x86/publish/*.*
